version: "3.8"

services:
  db:
    image: postgres:15.5-alpine3.19
    env_file:
      - .env
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: